#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : talloc
Version  : 2.1.10
Release  : 18
URL      : https://www.samba.org/ftp/talloc/talloc-2.1.10.tar.gz
Source0  : https://www.samba.org/ftp/talloc/talloc-2.1.10.tar.gz
Summary  : A hierarchical pool based memory system with destructors
Group    : Development/Tools
License  : LGPL-3.0+
Requires: talloc-legacypython
Requires: talloc-lib
Requires: talloc-python
BuildRequires : acl-dev
BuildRequires : attr-dev
BuildRequires : libaio-dev
BuildRequires : python-dev
BuildRequires : zlib-dev
Patch1: 0001_fix_default_install_path.patch
Patch2: 0002_fix_waf_options.patch

%description
See http://code.google.com/p/waf/ for more information on waf
You can get a svn copy of the upstream source with:

%package dev
Summary: dev components for the talloc package.
Group: Development
Requires: talloc-lib
Provides: talloc-devel

%description dev
dev components for the talloc package.


%package legacypython
Summary: legacypython components for the talloc package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the talloc package.


%package lib
Summary: lib components for the talloc package.
Group: Libraries

%description lib
lib components for the talloc package.


%package python
Summary: python components for the talloc package.
Group: Default
Requires: talloc-legacypython

%description python
python components for the talloc package.


%prep
%setup -q -n talloc-2.1.10
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1513085561
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1513085561
rm -rf %{buildroot}
%make_install
## make_install_append content
mkdir mkdir -p %{buildroot}/usr/lib64/
mv %{buildroot}/usr/lib/*.so* %{buildroot}/usr/lib64/
## make_install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libpytalloc-util.so
/usr/lib64/libtalloc.so
/usr/lib64/pkgconfig/pytalloc-util.pc
/usr/lib64/pkgconfig/talloc.pc

%files legacypython
%defattr(-,root,root,-)
%exclude /usr/lib/python2.7/site-packages/talloc.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpytalloc-util.so.2
/usr/lib64/libpytalloc-util.so.2.1.10
/usr/lib64/libtalloc.so.2
/usr/lib64/libtalloc.so.2.1.10

%files python
%defattr(-,root,root,-)
